### ISSUE TITLE
Dragging a GameObject with a Monobehaviour script implementing a required interface does not work

### ISSUE THREAD

**Issue by AndyW19** [adammyhre/Unity-Serialized-Interface#1]
Not exactly sure if I am doing something wrong but I am trying to assign a reference by dragging a gameobject that contains a script that implements the required interface. However it doesn't seem to work.

In my setup script I have:

```
[SerializeField] private InterfaceReference<IMapGenerator> _mapGeneratorInterface;
```

![Unity_MJ4IiqsNMp](https://github.com/user-attachments/assets/c520174a-7203-4fe0-89e7-9c12ba6be037)

I then have a GameObject in the scene with a `MapGenerationManager` monobehaviour that implements the `IMapGenerator` interface. 

```
public class MapGenerationManager : MonoBehaviour, IMapGenerator
```

I would assume dragging the gameobject into the field would work but it doesn't.
![Unity_Px6kwPgv1c](https://github.com/user-attachments/assets/d233d3c1-475e-4ab8-879f-ce30b0756cb1)

I think it may be due to this line in `InterfaceReferenceDrawer` (line 24)

```
            if (args.InterfaceType.IsAssignableFrom(assignedObject.GetType())) {
                if (assignedObject is GameObject gameObject) {
                    var component = gameObject.GetComponent(args.InterfaceType);

                    ValidateAndAssignObject(underlyingProperty, component, gameObject.name, args.InterfaceType.Name);
                }
                else {
                    ValidateAndAssignObject(underlyingProperty, assignedObject, assignedObject.GetType().Name,
                        args.InterfaceType.Name);
                }
            }

```

Removing the first `if` seems to fix the issue. If I am understanding this correctly, the first if check should be happening after we check if the `assignedObject` is a GameObject?

Running Unity 6000.0.25f1.

**Comment by adammyhre** [comment]
Thanks for the detailed report.  I was able to replicate and pushed a fix.  Let me know if that solves the issue.

**Comment by AndyW19** [comment]
Just verified that it is now working, thanks!
